#!/bin/bash

docker run \
       --rm \
       -it \
       --name my-maven-project \
       -v "$HOME/.m2:/var/maven/.m2" \
       -v "$(pwd)":/usr/src/mymaven \
       -w /usr/src/mymaven \
       -u "$(id -u)":"$(id -g)" \
       maven:3.3.9-jdk-8 \
       mvn -Duser.home=/var/maven --settings /var/maven/.m2/settings.xml -f com.gratex.oomph.task.server.parent clean package
