#!/bin/bash

#mkdir /tmp/.m2

#docker run \
#       -it \
#       --rm \
#       --name my-maven-project \
#       --privileged=true \
#       --userns=host \
#       -e "HOME=$HOME" \
#       -e "MAVEN_CONFIG=$HOME/.m2" \
#       -v "$HOME/.m2:$HOME/.m2" \
#       -v "$(pwd):$HOME/project" \
#       -w "$HOME/project" \
#       -u "$(id -u)":"$(id -g)" \
#       maven:3.3.9-jdk-8 \
#       mvn -Duser.home="$HOME"  --settings "$HOME/.m2/settings.xml" -f com.gratex.oomph.task.server.parent clean package

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


docker run \
       -it \
       --rm \
       --name my-maven-project \
       --privileged=true \
       --userns=host \
       -v "$HOME/.m2:/root/.m2" \
       -v "$PWD:/project" \
       -w "/project" \
       maven:3.5.0-jdk-8 \
       /bin/bash -c "mvn -f com.gratex.oomph.task.server.parent/pom.xml clean package && chown -R ""$(id -u):$(id -g)"" /project"



#       -u "$(id -u)":"$(id -g)" \
#       /bin/bash
#       --userns=host \
#       --rm \
#       -v "/tmp/.m2:/root/.m2" \

